project_id = "xlobevmhzimxjtpiontf"

[functions.suggest-campaign-steps]
verify_jwt = false

[functions.ask-joe]
verify_jwt = false

[functions.process-sequence-emails]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.match-entity]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.microsoft-oauth]
verify_jwt = false

[functions.microsoft-webhook]
verify_jwt = false
