import type { SupabaseClient } from "@supabase/supabase-js";
import { embedDocuments } from "./voyage.js";

/**
 * Writer for the unified `search_documents` index (the one Joe searches
 * via match_search_documents). One row per source object, keyed by
 * (source_kind, source_id). The `fts` column is GENERATED by Postgres
 * from title/subtitle/body — never set it here. `embedding` is a
 * Voyage voyage-finance-2 1024-dim vector we compute on the body.
 */

export interface SearchDoc {
  source_kind: string;          // 'resume' | 'note' | 'call_note' | ...
  source_id: string;            // the source row id, as text
  title?: string | null;
  subtitle?: string | null;
  body: string;                 // the text that gets embedded + FTS'd
  person_id?: string | null;
  candidate_id?: string | null;
  contact_id?: string | null;
  company_id?: string | null;
  job_id?: string | null;
  send_out_id?: string | null;
  task_id?: string | null;
  role_context?: string | null;
  url?: string | null;
  metadata?: Record<string, any> | null;
  source_updated_at?: string | null;
}

/** Max inputs per Voyage call. Keep modest — large bodies are truncated
 *  to 8k chars each inside embedDocuments. */
const EMBED_BATCH = 32;

/**
 * Embed + upsert a batch of documents into search_documents. Rows with
 * an empty body are skipped (nothing to embed). Upsert is keyed on the
 * (source_kind, source_id) unique index, so re-indexing an updated
 * source row overwrites in place rather than duplicating.
 *
 * Returns the number of rows written.
 */
export async function indexSearchDocuments(
  supabase: SupabaseClient,
  docs: SearchDoc[],
): Promise<number> {
  const usable = docs.filter((d) => d.source_id && (d.body || "").trim().length > 0);
  if (usable.length === 0) return 0;

  let written = 0;
  for (let i = 0; i < usable.length; i += EMBED_BATCH) {
    const slice = usable.slice(i, i + EMBED_BATCH);
    const embeddings = await embedDocuments(slice.map((d) => buildEmbedText(d)));

    const rows = slice.map((d, j) => ({
      source_kind: d.source_kind,
      source_id: d.source_id,
      title: d.title ?? null,
      subtitle: d.subtitle ?? null,
      body: d.body,
      person_id: d.person_id ?? null,
      candidate_id: d.candidate_id ?? null,
      contact_id: d.contact_id ?? null,
      company_id: d.company_id ?? null,
      job_id: d.job_id ?? null,
      send_out_id: d.send_out_id ?? null,
      task_id: d.task_id ?? null,
      role_context: d.role_context ?? null,
      url: d.url ?? null,
      metadata: d.metadata ?? null,
      source_updated_at: d.source_updated_at ?? null,
      embedding: embeddings[j] as any,
      indexed_at: new Date().toISOString(),
    }));

    const { error } = await supabase
      .from("search_documents")
      .upsert(rows as any, { onConflict: "source_kind,source_id" });
    if (error) throw new Error(`search_documents upsert failed: ${error.message}`);
    written += rows.length;
  }
  return written;
}

/** Embed on title + subtitle + body so the vector carries the same
 *  context the FTS column weights. */
function buildEmbedText(d: SearchDoc): string {
  return [d.title, d.subtitle, d.body].filter(Boolean).join("\n").trim();
}
