-- Audit fix 1b: the contacts compat view never exposed primary_email / location_text
-- after the people-table column renames (email -> primary_email, location -> location_text),
-- so any caller selecting contacts.primary_email failed ~every 5 min (visible in the
-- Postgres logs all day). Append the canonical names as additive compat columns.
CREATE OR REPLACE VIEW public.contacts AS
 SELECT id,
    company_id,
    first_name,
    last_name,
    full_name,
    primary_email AS email,
    phone,
    linkedin_url,
    title,
    department,
    status,
    owner_user_id AS owner_id,
    created_at,
    updated_at,
    last_contacted_at AS last_reached_out_at,
    last_responded_at,
    owner_user_id,
    notes,
    last_contacted_at,
    last_responded_at AS last_replied_at,
    linkedin_profile_text,
    linkedin_headline,
    linkedin_current_company,
    linkedin_current_title,
    linkedin_location,
    linkedin_last_synced_at,
    NULL::tsvector AS linkedin_search,
    ai_search_text,
    unipile_sales_nav_id,
    unipile_provider_id,
    avatar_url,
    profile_picture_url,
    linkedin_profile_data,
    unipile_resolve_status,
    company_name,
    created_by_user_id AS user_id,
    last_comm_channel,
    linkedin_enriched_at,
    linkedin_enrichment_source,
    last_sequence_sentiment,
    last_sequence_sentiment_note,
    unipile_recruiter_id,
    unipile_classic_id,
    location_text AS location,
    work_email,
    personal_email,
    mobile_phone,
    roles,
    linked_contact_id AS linked_candidate_id,
    is_stub,
    secondary_emails,
    primary_email,
    location_text
   FROM people
  WHERE type = 'client'::text;
