-- ============================================================================
-- Fix missing RLS on resumes table and add storage policies for resumes bucket
-- ============================================================================

-- 0. Create resumes table if it doesn't exist (was never created in tracked migrations)
CREATE TABLE IF NOT EXISTS public.resumes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id UUID REFERENCES public.candidates(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  file_name TEXT,
  file_url TEXT,
  mime_type TEXT,
  file_size INTEGER,
  raw_text TEXT,
  parsed_json JSONB,
  ai_summary TEXT,
  parse_status TEXT,
  parse_error TEXT,
  source TEXT,
  storage_bucket TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resumes_candidate_id ON public.resumes(candidate_id);

-- 1. Enable RLS on resumes table
ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;

-- Match the team-access pattern used by formatted_resumes and other shared tables
CREATE POLICY "Authenticated full access resumes"
  ON public.resumes FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- 2. Create resumes storage bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', false)
ON CONFLICT (id) DO NOTHING;

-- 3. Storage RLS policies for resumes bucket
CREATE POLICY "Authenticated users can upload resumes"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'resumes');

CREATE POLICY "Authenticated users can read resumes"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'resumes');

CREATE POLICY "Authenticated users can update resumes"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'resumes');

CREATE POLICY "Authenticated users can delete resumes"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'resumes');

-- ============================================================================
-- 4. Create candidate_documents table (referenced in code but never migrated)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.candidate_documents (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id UUID NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  mime_type TEXT DEFAULT 'application/octet-stream',
  file_size INTEGER,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.candidate_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated full access candidate_documents"
  ON public.candidate_documents FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_candidate_documents_candidate_id
  ON public.candidate_documents(candidate_id);

CREATE TRIGGER update_candidate_documents_updated_at
  BEFORE UPDATE ON public.candidate_documents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================================
-- 5. Create ai_call_notes table (referenced in code but never migrated)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.ai_call_notes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id UUID REFERENCES public.candidates(id) ON DELETE CASCADE,
  contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
  call_log_id UUID REFERENCES public.call_logs(id) ON DELETE SET NULL,
  summary TEXT,
  action_items JSONB,
  transcript TEXT,
  sentiment TEXT,
  updated_candidates_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.ai_call_notes ENABLE ROW LEVEL SECURITY;

-- Team can read all call notes, service_role manages writes (generated by AI)
CREATE POLICY "Authenticated users can read ai_call_notes"
  ON public.ai_call_notes FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated full access ai_call_notes"
  ON public.ai_call_notes FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_ai_call_notes_candidate_id
  ON public.ai_call_notes(candidate_id);

CREATE INDEX IF NOT EXISTS idx_ai_call_notes_contact_id
  ON public.ai_call_notes(contact_id);
