// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The project's public URL + publishable (anon) key. These are safe to ship in
// the browser bundle (RLS protects the data) and are hardcoded as the source of
// truth so the app always reaches the correct Supabase project. Previously these
// were read from VITE_* env vars; when those were unset/misconfigured in the
// deploy, every auth + data request failed with "Failed to fetch" because the
// client pointed at the wrong (or no) host. Hardcoding matches how this file is
// generated and removes that failure mode.
const SUPABASE_URL = 'https://xlobevmhzimxjtpiontf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_cs_6WLpIGSD2ez2tVTUkvA_rrtbF5lP';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});