// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhtmuvsrjvvqobrimqhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFodG11dnNyanZ2cW9icmltcWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MDY4ODcsImV4cCI6MjA4ODE4Mjg4N30.WMDoL2v8FiFh6NQPcxFuK6DpTLnjZYcPrE2Cr2wXUsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});